name = "VanillaQT"
author = "Mathias Sven"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b8a4e850fc08a09f9ee77476249ac66afaaecec8a6b1007683bf6986d3ff623"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
datapack-folder = "global_packs/required_data"
