name = "VanillaQT"
author = "Mathias Sven"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7378346d3e2501419035c0e565615a52111df275c240f04830130082734398ed"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
datapack-folder = "global_packs/required_data"
