#The directory to run the game in.
hmc.gamedir=./.minecraft

# This is where assets and libraries are stored.
hmc.mcdir=./mc-libassets

# Auto download will not work on Nix
hmc.auto.download.java=false
