#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 21 11:27:32 WEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=photon_v1.3b.zip
