# +-------------------------------------------------------+
# | BlueMap Banners main config file                      |
# |   Modify this file to change BlueMap Banners settings |
# +-------------------------------------------------------+


notifyPlayerOnBannerPlace=true
notifyPlayerOnMarkerAdd=true
notifyPlayerOnMarkerRemove=true
notifyGlobalOnMarkerRemove=false
markerAddInstantOnBannerPlace=false
markerAddWithOriginalName=false
markerMaxViewDistance=10000000
bluemapUrl=https://minecraft.mathiassven.com/
sendMetrics=false
storageType=JSON
storageJdbcUrl=jdbc:mariadb://localhost:3306/bluemap-banners
storageJdbcUser=root
storageJdbcPassword=root
storageJdbcJar=path/to/your/mariadb-java-client-3.0.7.jar
storageJdbcEntry=org.mariadb.jdbc.Driver
