name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: DeterminateSystems/nix-installer-action@v22
      - if: ${{ !env.ACT }}
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - id: pack_toml
        run:
          nix shell nixpkgs#yq -c tomlq -r '
            paths(scalars) as $p
            | "\($p | map(tostring) | join("."))=\(getpath($p) | tojson)"
          ' pack.toml >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          name="${{ steps.pack_toml.outputs.name }}"
          version="${{ steps.pack_toml.outputs.version }}"

          mkdir release
          nix run .#packwiz -- mr export -o "./release/$name-$version.mrpack"
          nix run .#mk-prismpack -- -o "./release/$name.zip"

      - name: Release
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v3.0.0
        with:
          files: release/*

  pages:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v5
